### ISSUE TITLE
Index and Tree status not detected

### ISSUE THREAD

**Issue by nicholas-cwb** [planetscale/ghcommit-action#43]
```
Filename: artefact.txt
Index Status: ?
Tree Status: ?
Filename: artefact.txt
-----------------------------
No changes detected, exiting
```

Some how it detectes the filename but index and tree status is `?`

My github action:
```yml
name: fmt

on:
  pull_request:
    branches:
       - main

jobs:
  generate-txt:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      # Run steps that make changes to the local repo here.

      # Commit all changed files back to the repository
      - uses: planetscale/ghcommit-action@v0.1.6
        with:
          commit_message: "generate txt"
          repo: ${{ github.repository }}
          branch: ${{ github.head_ref || github.ref_name }}
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
```
