### ISSUE TITLE
Still doesn't work on ARM

### ISSUE THREAD

**Issue by NikolayMetchev** [planetscale/ghcommit-action#81]
Following on from https://github.com/planetscale/ghcommit-action/issues/66#issuecomment-2403385396

I tried it and the action behaves identically to before:

Run planetscale/ghcommit-action@d4176bfacef926cc2db351eab20398dfc2f593b5
  with:
    commit_message: Gradle Verification Metadata
    repo: paxosglobal/messaging
    branch: arm-gha-[2](https://github.com/paxosglobal/messaging/actions/runs/11280459749/job/31373484356?pr=4143#step:6:2)
    empty: false
    file_pattern: .
  env:
    AWS_DEFAULT_REGION: us-east-1
    AWS_REGION: us-east-1
    AWS_ACCESS_KEY_ID: ***
    AWS_SECRET_ACCESS_KEY: ***
    AWS_SESSION_TOKEN: ***
    JAVA_HOME: /codebuild/output/src2715070986/src/actions-runner/_work/_tool/Java_Corretto_jdk/17.0.12-7.1/arm6[4](https://github.com/paxosglobal/messaging/actions/runs/11280459749/job/31373484356?pr=4143#step:6:4)
    JAVA_HOME_17_ARM64: /codebuild/output/src271[5](https://github.com/paxosglobal/messaging/actions/runs/11280459749/job/31373484356?pr=4143#step:6:5)070986/src/actions-runner/_work/_tool/Java_Corretto_jdk/17.0.12-7.1/arm[6](https://github.com/paxosglobal/messaging/actions/runs/11280459749/job/31373484356?pr=4143#step:6:6)4
    GRADLE_ACTION_ID: gradle/actions/setup-gradle
    GRADLE_USER_HOME: /root/.gradle
    GRADLE_BUILD_ACTION_SETUP_COMPLETED: true
    GRADLE_BUILD_ACTION_CACHE_RESTORED: true
    GRADLE_ENCRYPTION_KEY: ***
    DEVELOCITY_INJECTION_INIT_SCRIPT_NAME: gradle-actions.inject-develocity.init.gradle
    DEVELOCITY_AUTO_INJECTION_CUSTOM_VALUE: gradle-actions
    GITHUB_DEPENDENCY_GRAPH_ENABLED: false
    GITHUB_TOKEN: ***
/usr/local/bin/docker run --name c[7](https://github.com/paxosglobal/messaging/actions/runs/11280459749/job/31373484356?pr=4143#step:6:7)71c1a52a765e784cf[8](https://github.com/paxosglobal/messaging/actions/runs/11280459749/job/31373484356?pr=4143#step:6:8)81f4fc0e672bbc7a_0a171a --label 64c771 --workdir /github/workspace --rm -e "AWS_DEFAULT_REGION" -e "AWS_REGION" -e "AWS_ACCESS_KEY_ID" -e "AWS_SECRET_ACCESS_KEY" -e "AWS_SESSION_TOKEN" -e "JAVA_HOME" -e "JAVA_HOME_17_ARM64" -e "GRADLE_ACTION_ID" -e "GRADLE_USER_HOME" -e "GRADLE_BUILD_ACTION_SETUP_COMPLETED" -e "GRADLE_BUILD_ACTION_CACHE_RESTORED" -e "GRADLE_ENCRYPTION_KEY" -e "DEVELOCITY_INJECTION_INIT_SCRIPT_NAME" -e "DEVELOCITY_AUTO_INJECTION_CUSTOM_VALUE" -e "GITHUB_DEPENDENCY_GRAPH_ENABLED" -e "GITHUB_TOKEN" -e "INPUT_COMMIT_MESSAGE" -e "INPUT_REPO" -e "INPUT_BRANCH" -e "INPUT_EMPTY" -e "INPUT_FILE_PATTERN" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_W
Filename: gradle/verification-metadata.xml
Index Status:  
Tree Status: M
Filename: gradle/verification-metadata.xml
-----------------------------
/entrypoint.sh: line 77: /usr/bin/ghcommit: cannot execute binary file: Exec format error

Here is what the config looks like:
```
      - name: Push changes
        uses: planetscale/ghcommit-action@d4176bfacef926cc2db351eab20398dfc2f593b5 # v0.2.0
        with:
          commit_message: "Gradle Verification Metadata"
          repo: ${{ github.repository_owner }}/messaging
          branch: ${{ github.head_ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GHA_WRITE_TOKEN }}
```
